export const products = [
    {
        id: 1,
        title: "Cucumber",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 2,
        title: "Tomato",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 3,
        title: "Lettuce",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 4,
        title: "Onion",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 5,
        title: "Red Pepper",
        in_stock: false,
        ingredients: [],
    },
    {
        id: 6,
        title: "Olive Oil",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 7,
        title: "Vinegar",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 8,
        title: "Garlic",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 9,
        title: "Feta Cheese",
        in_stock: false,
        ingredients: [],
    },
    {
        id: 10,
        title: "Basil",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 11,
        title: "Avocado",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 12,
        title: "Chickpeas",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 13,
        title: "Quinoa",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 14,
        title: "Spinach",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 15,
        title: "Carrot",
        in_stock: true,
        ingredients: [],
    },
    {
        id: 16,
        title: "Greek Salad",
        in_stock: true,
        ingredients: [
            { product_id: 1, quantity: 1 },
            { product_id: 2, quantity: 1 },
            { product_id: 3, quantity: 1 },
            { product_id: 4, quantity: 1 },
            { product_id: 5, quantity: 1 },
            { product_id: 9, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
    {
        id: 17,
        title: "Ceasar Salad",
        in_stock: true,
        ingredients: [
            { product_id: 3, quantity: 2 },
            { product_id: 8, quantity: 1 },
            { product_id: 9, quantity: 1 },
            { product_id: 7, quantity: 1 },
        ],
    },
    {
        id: 18,
        title: "Tomato Basil Salad",
        in_stock: true,
        ingredients: [
            { product_id: 2, quantity: 2 },
            { product_id: 10, quantity: 1 },
            { product_id: 6, quantity: 1 },
            { product_id: 7, quantity: 1 },
        ],
    },
    {
        id: 19,
        title: "Quinoa Avocado Bowl",
        in_stock: true,
        ingredients: [
            { product_id: 13, quantity: 1 },
            { product_id: 11, quantity: 1 },
            { product_id: 2, quantity: 1 },
            { product_id: 14, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
    {
        id: 20,
        title: "Chickpea Salad",
        in_stock: true,
        ingredients: [
            { product_id: 3, quantity: 1 },
            { product_id: 12, quantity: 1 },
            { product_id: 15, quantity: 1 },
            { product_id: 6, quantity: 1 },
            { product_id: 7, quantity: 1 },
        ],
    },
    {
        id: 21,
        title: "Mediterranean Plate",
        in_stock: true,
        ingredients: [
            { product_id: 1, quantity: 1 },
            { product_id: 2, quantity: 1 },
            { product_id: 11, quantity: 1 },
            { product_id: 5, quantity: 1 },
            { product_id: 9, quantity: 1 },
        ],
    },
    {
        id: 22,
        title: "Hummus Wrap",
        in_stock: false,
        ingredients: [
            { product_id: 12, quantity: 1 },
            { product_id: 3, quantity: 1 },
            { product_id: 4, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
    {
        id: 23,
        title: "Detox Salad",
        in_stock: true,
        ingredients: [
            { product_id: 14, quantity: 1 },
            { product_id: 15, quantity: 1 },
            { product_id: 13, quantity: 1 },
            { product_id: 6, quantity: 1 },
            { product_id: 7, quantity: 1 },
        ],
    },
    {
        id: 24,
        title: "Avocado Toast",
        in_stock: true,
        ingredients: [
            { product_id: 11, quantity: 1 },
            { product_id: 6, quantity: 1 },
            { product_id: 10, quantity: 1 },
        ],
    },
    {
        id: 25,
        title: "Buddha Bowl",
        in_stock: true,
        ingredients: [
            { product_id: 13, quantity: 1 },
            { product_id: 14, quantity: 1 },
            { product_id: 12, quantity: 1 },
            { product_id: 15, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
    {
        id: 26,
        title: "Rainbow Veggie Plate",
        in_stock: true,
        ingredients: [
            { product_id: 1, quantity: 1 },
            { product_id: 2, quantity: 1 },
            { product_id: 3, quantity: 1 },
            { product_id: 4, quantity: 1 },
            { product_id: 15, quantity: 1 },
        ],
    },
    {
        id: 27,
        title: "Tomato Bruschetta",
        in_stock: true,
        ingredients: [
            { product_id: 2, quantity: 1 },
            { product_id: 10, quantity: 1 },
            { product_id: 8, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
    {
        id: 28,
        title: "Herb Salad",
        in_stock: true,
        ingredients: [
            { product_id: 14, quantity: 1 },
            { product_id: 10, quantity: 1 },
            { product_id: 6, quantity: 1 },
            { product_id: 7, quantity: 1 },
        ],
    },
    {
        id: 29,
        title: "Spicy Avocado Dip",
        in_stock: true,
        ingredients: [
            { product_id: 11, quantity: 1 },
            { product_id: 5, quantity: 1 },
            { product_id: 8, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
    {
        id: 30,
        title: "Classic Caprese",
        in_stock: true,
        ingredients: [
            { product_id: 2, quantity: 1 },
            { product_id: 10, quantity: 1 },
            { product_id: 9, quantity: 1 },
            { product_id: 6, quantity: 1 },
        ],
    },
];
